-- Table STUDENT --------------------
CREATE TABLE STUDENT (
	Name VARCHAR(30) NOT NULL,
	Student_number INTEGER NOT NULL,
	Class INTEGER NOT NULL,
	Major VARCHAR(10) NOT NULL,
	PRIMARY KEY (Student_number));

INSERT INTO STUDENT VALUES ('Smith', 17, 1, 'CS');
INSERT INTO STUDENT VALUES ('Brown', 8, 2, 'CS');

-- Table COURSE --------------------
CREATE TABLE COURSE(
	Course_name VARCHAR(30) NOT NULL,
	Course_number VARCHAR(15) NOT NULL,
	Credit_hours INTEGER NOT NULL,
	Department VARCHAR(10) NOT NULL,
	PRIMARY KEY (Course_number));

INSERT INTO COURSE VALUES ('Intro to Computer Science', 'CS1310', 4, 'CS');
INSERT INTO COURSE VALUES ('Data Structures', 'CS3320', 4, 'CS');
INSERT INTO COURSE VALUES ('Discrete Mathematics', 'MATH2410', 3, 'MATH');
INSERT INTO COURSE VALUES ('Database', 'CS3380', 3, 'CS');

-- Table SECTION --------------------
CREATE TABLE SECTION(
	Section_identifier INTEGER NOT NULL,
	Course_number VARCHAR(15) NOT NULL,
	Semester VARCHAR(10) NOT NULL,
	Year INTEGER NOT NULL,
	Instructor VARCHAR(30) NOT NULL,
	PRIMARY KEY (Section_identifier),
	FOREIGN KEY (Course_number) REFERENCES COURSE(Course_number));

INSERT INTO SECTION VALUES (85,'MATH2410', 'Fall', 07, 'King');
INSERT INTO SECTION VALUES (92,'CS1310', 'Fall', 07, 'Anderson');
INSERT INTO SECTION VALUES (102,'CS3320', 'Spring', 08, 'Knuth');
INSERT INTO SECTION VALUES (112,'MATH2410', 'Fall', 08, 'Chang');
INSERT INTO SECTION VALUES (119,'CS1310', 'Fall', 08, 'Anderson');
INSERT INTO SECTION VALUES (135,'CS3380', 'Fall', 08, 'Stone');

-- Table GRADE_REPORT --------------------
CREATE TABLE GRADE_REPORT(
	Student_number INTEGER NOT NULL,
	Section_identifier INTEGER NOT NULL,
	GRADE VARCHAR(5) NOT NULL,
	FOREIGN KEY (Student_number) REFERENCES STUDENT(Student_number),
	FOREIGN KEY (Section_identifier) REFERENCES SECTION(Section_identifier));

INSERT INTO GRADE_REPORT VALUES (17, 112, 'B');
INSERT INTO GRADE_REPORT VALUES (17, 119, 'C');
INSERT INTO GRADE_REPORT VALUES (8, 85, 'A');
INSERT INTO GRADE_REPORT VALUES (8, 92, 'A');
INSERT INTO GRADE_REPORT VALUES (8, 102, 'B');
INSERT INTO GRADE_REPORT VALUES (8, 135, 'A');

-- Table PREREQUISITE --------------------
CREATE TABLE PREREQUISITE(
	Course_number VARCHAR(15) NOT NULL,
	Prerequisite_number VARCHAR(15) NOT NULL,
	FOREIGN KEY (Course_number) REFERENCES COURSE(Course_number),
	FOREIGN KEY (Prerequisite_number) REFERENCES COURSE(Course_number));

INSERT INTO PREREQUISITE VALUES ('CS3380', 'CS3320');
INSERT INTO PREREQUISITE VALUES ('CS3380', 'MATH2410');
INSERT INTO PREREQUISITE VALUES ('CS3320', 'CS1310');